### ISSUE TITLE
Show junctions numbers on Motorway even at lowest zoom level

### ISSUE THREAD

**Issue by aliexalter** [heremaps/maps-api-for-javascript-examples#10]
How can I tell API to show me the junctions and street names on low zoom level. For example
When user zoom in Motorway junction appear, when user zoom out after junction number/name disappears. I want to show junction name/number at all zoom levels.

**Comment by oleksmarkh** [comment]
Vector tiles include different data on different zoom levels, so after zooming out far enough some data (e.g. street-level) might just not be there anymore. On those tiles where it's still there, there might be a lot of other data competing to be rendered on the same screen space - some of it wins over the other based on priorities, styling, collision logic etc.
