### ISSUE TITLE
CORS Blocks on Localhost while Developing Figma Plugin

### ISSUE THREAD

**Issue by degatt2** [heremaps/maps-api-for-javascript-examples#104]
I'm developing a Figma plugin to capture images from your map. 
Following the example:
https://developer.here.com/documentation/examples/maps-js/styles/change-style-at-load

Produce the following error:
**Access to XMLHttpRequest at 'http://js.api.here.com/v3/3.1/styles/omv/miami/normal.day.yaml' from origin 'http://localhost:8000' has been blocked by CORS policy: No 'Access-Control-Allow-Origin' header is present on the requested resource.**

Funny enough, after I change the styles, the map works on Localhost. Unfortunately it doesn't work as a figma plugin because this error.

**Comment by oleksmarkh** [comment]
Hi @degatt2! Could you please check what's the value of the `origin` **request** header being sent from inside a Figma plugin? Does it also happen when you're developing on localhost without a Figma plugin, like on a simple HTML page? Normally, when the `origin` request header is sent, the corresponding CORS headers are sent back. Also please note that `http:` requests are redirected with 301 to `https:` for that resource.

**Comment by sackh** [comment]
Hi @oleksmarkh - I am also getting the same error. Please find attached the HTML example file for the same.
[demo.txt](https://github.com/heremaps/maps-api-for-javascript-examples/files/6040897/demo.txt)

**Comment by sackh** [comment]
This issue is resolved for me. just use `https` instead of `http` in URL:
http://js.api.here.com/v3/3.1/styles/omv/miami/normal.day.yaml

**Comment by degatt2** [comment]
I tried your code attached above and it didn't work for me.
I made it work loading the japan styles... which is fine for now, since my
plan is to load my own styles.



*Dega.*
Contemporary artist
phone. +49 1715523165
address. Wöhlertstraße 18, 10115 Berlin
web. http://degafolio.info/paintings/

**Comment by sackh** [comment]
sorry forgot to mention one more thing remove headers from line: 36 {headers: {'access-control-allow-origin': '*'}

**Comment by oleksmarkh** [comment]
As I understand, CORS issues aren't tight to the Figma Plugin environment itself, rather to actual style URLs. We can reopen this one in future to track down particular root causes of unexpected CORS blocking, having some isolated and reproducible examples. Thank you for the reports!
