### ISSUE TITLE
WKT on the map

### ISSUE THREAD

**Issue by bogdartysh** [heremaps/maps-api-for-javascript-examples#11]
is it possible to add some WKT on the Map example, like:
https://bogdartysh.github.io/energia/wkt/
https://arthur-e.github.io/Wicket/sandbox-gmaps3.html
https://jsfiddle.net/asnyder14/9dxbcr4f/embedded/result/
?

**Comment by ttobis** [comment]
Hello bogdartysh,

yes there is a solution:
`polygon = map.addObject(new H.map.Polygon(H.util.wkt.toGeometry('MULTIPOLYGON (((40 40, 20 45, 45 30, 40 40)), ((20 35, 10 30, 10 10, 30 5, 45 20, 20 35), (30 20, 20 15, 20 25, 30 20)))')));
map.getViewModel().setLookAtData({bounds: polygon.getBoundingBox()})`
