### ISSUE TITLE
how drawing polygon

### ISSUE THREAD

**Issue by 463728946** [heremaps/maps-api-for-javascript-examples#123]
Hello!

I want this：
![847ef0e23f36969f4e9490eae1a5b37](https://user-images.githubusercontent.com/40827525/153103716-508c628d-72e4-449f-ac20-e72348e0dc90.png)

It looks like：[drawing-control](https://developer.here.com/documentation/maps/3.1.30.7/api_reference/H.venues.Drawing.html)

var venuesProvider = new H.venues.Provider()  //  property 'venues' does not exist"@here/maps-api-for-javascript": "^1.30.9"
venuesService.loadVenue(VENUE_ID).then(venue => {`
  venuesProvider.addVenue(venue);
  venuesProvider.setActiveVenue(venue);

  var drawingControl = new H.venues.ui.DrawingControl(venue);
  ui.addControl('drawing-control', drawingControl);
});

**Comment by dbacarel** [comment]
Hi,

the library doesn't provide a UI control to draw shapes, the ```drawing-control``` from Venues module serves other purposes.

You can however create, add and resize shapes using the API, see the following demo link:
- Resize polygons: [demo](https://heremaps.github.io/maps-api-for-javascript-examples/resizable-polygon/demo.html) - [source](https://github.com/heremaps/maps-api-for-javascript-examples/blob/master/resizable-polygon/demo.js)
- Resize circle: [demo](https://heremaps.github.io/maps-api-for-javascript-examples/resizable-circle/demo.html) - [source](https://github.com/heremaps/maps-api-for-javascript-examples/blob/master/resizable-circle/demo.js)
- Resize polyline: [demo](https://heremaps.github.io/maps-api-for-javascript-examples/resizable-polyline/demo.html) - [source](https://github.com/heremaps/maps-api-for-javascript-examples/blob/master/resizable-polyline/demo.js)
- Resize rectangle: [demo](https://heremaps.github.io/maps-api-for-javascript-examples/resizable-rect/demo.html) - [source](https://github.com/heremaps/maps-api-for-javascript-examples/blob/master/resizable-rect/demo.js)

**Comment by 463728946** [comment]
thx @dbacarel ,

i find [demo](https://demo.support.here.com/examples/v3.1/gfe_draw_upload_layer)
 
enduser can drawing any polygon on map

how can I do like demo
