### ISSUE TITLE
a tag not working if Here maps default pan/zoom interactions are implemented

### ISSUE THREAD

**Issue by nikesh-devaki** [heremaps/maps-api-for-javascript-examples#13]
I am trying to import Here maps into one of our webpage. 

> HTML content

`                <mat-expansion-panel [expanded]="true">
                    <mat-expansion-panel-header>
                        <mat-panel-title>Location Summary</mat-panel-title>
                    </mat-expansion-panel-header>
                    <mat-card fxFlex="100" class="no-padding">
                     <div class="mapcontainer" style="width:100%; height:500px" id="mapContainer" ></div>
                    </mat-card>
                </mat-expansion-panel>   
               `

> Java Script

` this.map = new H.Map(<HTMLElement> document.getElementById("mapContainer),
                         this.mapTypes.normal.map);
 let behavior = new H.mapevents.Behavior(new H.mapevents.MapEvents(this.map));`

If Here maps mapcontainer is successfully initialized with zoom and drag interactins are implemented , then following a tag does not work. On click of hyperlink does not take to me to new page. But works fine if I try to right click hyperlink and open in new tab. 

`<a *ngFor="let s of getSzValues(z.subzones)"  [ngClass]='active' href="/HealthDetail/SZ" routerLink="/HealthDetail/{{s[0]}}">   {{s[1]}}</a>`

Not able to narrow down root cause. Any reference or pointers will be helpful.

**Comment by ttobis** [comment]
Hello nikesh-dev,

try this code:
`this.map = new H.Map(document.getElementById("mapContainer"), this.mapTypes.normal.map); 
let behavior = new H.mapevents.Behavior(new H.mapevents.MapEvents(this.map));`
