### ISSUE TITLE
Delay to open 10000+ data, page stuck and alert display to exit page or wait on chrome

### ISSUE THREAD

**Issue by HARSHA190599** [heremaps/maps-api-for-javascript-examples#133]
Data display as per latitude and longitude on map with info bubble. But when data size 10000+ these data can't display quickly, it take 1 min+ time or sometimes stuck the map and show nothing.

**Comment by dbacarel** [comment]
Hi @HARSHA190599 , could you share a minimal code snippet to reproduce this issue?

**Comment by dbacarel** [comment]
Closing the issue for inactivity. Please reopen it with a reproducible code.
