### ISSUE TITLE
CSS validate issue mapsjs-ui.css 

### ISSUE THREAD

**Issue by joshin2017** [heremaps/maps-api-for-javascript-examples#14]
Hello Team,

Library https://js.api.here.com/v3/3.0/mapsjs-ui.css is not validating the css in https://jigsaw.w3.org/css-validator

Can u please remove extra "," present in css?
![image](https://user-images.githubusercontent.com/28758258/56026075-07f83b00-5d31-11e9-963f-af0b382eacca.png)
![image](https://user-images.githubusercontent.com/28758258/56026119-23fbdc80-5d31-11e9-9086-98599fc62b6e.png)

Thanks
Joshin

**Comment by sschuberth** [comment]
Thanks for the report. The `mapsjs-ui.css` file is not part of this project, but we'll forward the report internally to the right people.
