### ISSUE TITLE
Is there any specific time to live for routeHandle?

### ISSUE THREAD

**Issue by vadym1930** [heremaps/maps-api-for-javascript-examples#142]
In the [documentation](https://developer.here.com/documentation/routing-api/dev_guide/topics/route-handle.html) it says 
>   A route handle encodes a path from a previously calculated route. It can be used to compactly cache a route for a brief amount of time. Thus, it can be used to retrieve more data along the route and get updated traffic information.

  'brief amount of time' definition is confusing and not clear-cut enough. Do we have any accurate specific time restrictions for a `routeHandle` to be valid?

**Comment by dbacarel** [comment]
Hi @vadym1930, closing this issue as this is not related to HERE Maps API for JS. 

You can send your question/feedback to the [HERE Routing API v8](https://www.here.com/docs/bundle/routing-api-developer-guide-v8/page/topics/route-handle.html) directly using the "Feedback" button.
