### ISSUE TITLE
Remove/explain dependencies, especially iframe-height.js?

### ISSUE THREAD

**Issue by mflaxman10** [heremaps/maps-api-for-javascript-examples#19]
For sample code, these examples have a lot of non-standard and unexplained dependencies.
There are three separate css files, which is fine for production but not great for sample code.

I'm currently blocked by this one:

iframe-height.js

which is referenced from all of the examples as:
    <script type="text/javascript" src='../js-examples-rendering-helpers/iframe-height.js'></script> 

 but I couldn't find it in an archive search, or guess what it is supposed to do

**Comment by mkarpicki** [comment]
good catch.
will be fixed soon - please just remove this line when using example for now

**Comment by greenred123** [comment]
We have removed the reference to iframe-height.js, thanks for alerting us to that mistake.

We are using a number of css files so we can use the source code in this repo to render the examples in a number of contexts - including on our developer portal (developer.here.com) and jsfiddle.
