### ISSUE TITLE
Clustering with Here Maps API v3 on Geojson or KML files

### ISSUE THREAD

**Issue by wlazi** [heremaps/maps-api-for-javascript-examples#21]
I wonder how I can use clustering directly on geojson or kml data ?

**Comment by germanz** [comment]
We use in-browser clustering based on certain data point structure. You can load the GeoJSON/KML file, convert it, and use the [clustering as described here](https://developer.here.com/documentation/maps/3.1.16.1/dev_guide/topics/clustering.html).

For big datasets you might want to use server-based clustering. For example [clustering feature from the HERE XYZ](https://www.here.xyz/api/devguide/usingclustering/).
