### ISSUE TITLE
How to add a overlay to a polygon?

### ISSUE THREAD

**Issue by kleber7777** [heremaps/maps-api-for-javascript-examples#28]
In the guide section there is a example of how to add a [overlay to the map](https://developer.here.com/api-explorer/maps-js/maps/custom-tile-overlay). This works. But I need to add overlay to a polygon. Can i do this? I can't find a way to do this.

**Comment by kplotnik** [comment]
There is a map object `H.map.Overlay` that is defined by the `H.geo.Rect` and can have an arbitrary bitmap associated with it. No tiling is needed from you side for this object.

**Comment by kplotnik** [comment]
You can check [Image Overlay](https://heremaps.github.io/maps-api-for-javascript-examples/image-overlay/demo.html) example

**Comment by kleber7777** [comment]
@kplotnik yeah, this works for me. Thanks.
