### ISSUE TITLE
Canvas height problem

### ISSUE THREAD

**Issue by goors** [heremaps/maps-api-for-javascript-examples#5]
Hi,

sometimes maps renders ok but most of times it looks like explained here: 
https://stackoverflow.com/questions/44873578/how-to-fix-layout-with-heremaps

it is like map canvas height is not calculated correctly.

I hope that you an answer this.

**Comment by germanz** [comment]
Hi @goors. Sorry, but link you mentioned does not work. Can you please send a piece of code, so that we can better understand the problem?
