### ISSUE TITLE
Custom Marker HERE API 3.1

### ISSUE THREAD

**Issue by Mexikaner9** [heremaps/maps-api-for-javascript-examples#52]
I want to have a custom marker.
An example with the default marker works. 
http://nirvana.bplaced.net/20/ 
	
Unfortunately my example with the custom marker doesn't work. 
http://nirvana.bplaced.net/21/ 

What is wrong with my code? 

`function addMarkersToMap(map) {
  var icon = new H.map.Icon('images/marker.png');
  var myplaceMarker = new H.map.Marker({ lat: 49.302050, lng:10.571050 }, { icon: icon });
  map.addObject(myplaceMarker);
}

var platform = new H.service.Platform({
  'apikey': <API_KEY>
});
var defaultLayers = platform.createDefaultLayers();

var map = new H.Map(document.getElementById('map'),
  defaultLayers.vector.normal.map,{
  center: {lat:49.302050, lng:10.571050},
  zoom: 15,
  pixelRatio: window.devicePixelRatio || 1
});
window.addEventListener('resize', () => map.getViewPort().resize());

var behavior = new H.mapevents.Behavior(new H.mapevents.MapEvents(map));

var ui = H.ui.UI.createDefault(map, defaultLayers);

window.onload = function () {
  addMarkersToMap(map);
}`

Please help me.

**Comment by kjellski** [comment]
I see this in the middle of the map on your last example: 

<img width="402" alt="Screenshot 2019-08-12 at 07 47 51" src="https://user-images.githubusercontent.com/30225/62847245-8d86fa00-bcd5-11e9-9ae8-269ac29f997a.png">

Also, I would recommend getting new credentials and invalidating the one you publicly posted here. That API key is not something that should be made public AFAIK.

**Comment by Mexikaner9** [comment]
Thanks for your answer!
Unfortunately the marker is not displayed locally on my computer.

**Comment by kplotnik** [comment]
@Mexikaner9 what browser do you use? Do you access the page locally with the file:// protocol?

**Comment by Mexikaner9** [comment]
Google Chrome and Mozilla Firefox.

**Comment by chiragkoli** [comment]
@Mexikaner9 hello how did the custom marker work? can you tell me

**Comment by dbacarel** [comment]
Hi @chiragkoli, you can create your custom marker by adding an instance of `H.map.Icon` as a parameter when you create a `H.map.Marker`.

For example:
```javascript
const svgMarkup = '<svg height="100" width="100" xmlns="http://www.w3.org/2000/svg">' +
  '<circle cx="50" cy="50" r="40" stroke="black" stroke-width="3" fill="red" /></svg>';
const customIcon = new H.map.Icon(svgMarkup);
const customMarker = new H.map.Marker({lat: 41.8625, lng: -87.6166 }, {icon: customIcon});
```

More info in the API documentation:
https://developer.here.com/documentation/maps/topics_api/h-map-marker.html#h-map-marker
https://developer.here.com/documentation/maps/topics_api/h-map-icon.html#h-map-icon
