### ISSUE TITLE
Here map clear/remove direction from a to b

### ISSUE THREAD

**Issue by veera1908** [heremaps/maps-api-for-javascript-examples#57]
How to remove/clear routing location from a to b dynamically? i am using direction service. only remove direction not marker.

![Screenshot_2019-08-24 CMRL Stop](https://user-images.githubusercontent.com/47779880/63635666-7f948a00-c682-11e9-956a-cc72273d8563.png)

**Comment by kplotnik** [comment]
If I understood it correct you want to do some sort of a "rubber-band" routing. The only way to achieve it is to re-request the routing directions from the service and then add he new polyline to the map.
