### ISSUE TITLE
map-at-specified-location with a custom marker

### ISSUE THREAD

**Issue by Mexikaner9** [heremaps/maps-api-for-javascript-examples#6]
Hello,
I want to have the example
map-at-specified-location with a custom marker ( a PNG image).
but what code do I need???

https://github.com/heremaps/maps-api-for-javascript-examples/tree/master/map-at-specified-location

**Comment by Mexikaner9** [comment]
this is the Original code
`function moveMapToBerlin(map){
  map.setCenter({lat:52.51, lng:13.37});
  map.setZoom(14);
}

var platform = new H.service.Platform({
  app_id: '{YOUR_APP_ID}',
  app_code: '{YOUR_APP_CODE}',
  useCIT: true,
  useHTTPS: true
});
var defaultLayers = platform.createDefaultLayers();


var map = new H.Map(document.getElementById('map'),
  defaultLayers.normal.map);

// meine
window.addEventListener('resize', function () {
  map.getViewPort().resize();
});

var behavior = new H.mapevents.Behavior(new H.mapevents.MapEvents(map));

var ui = H.ui.UI.createDefault(map, defaultLayers);

moveMapToBerlin(map);`


And this is my code (not working):
`function moveMapToBerlin(map){
  map.setCenter({lat:52.51, lng:13.37});
  map.setZoom(14);
}

var platform = new H.service.Platform({
  app_id: '{YOUR_APP_ID}',
  app_code: '{YOUR_APP_CODE}',
  useCIT: true,
  useHTTPS: true
});
var defaultLayers = platform.createDefaultLayers();


var coordinates = {
  lat: 52.51,
  lng: 13.37
};
var marker = new H.map.Marker(coordinates);
map.addObject(marker);
var iconUrl = ‘marker.png’;
var iconOptions = {
	// The icon's size in pixel:
  size: new H.math.Size(26, 34),
	// The anchorage point in pixel, 
	// defaults to bottom-center
  anchor: new H.math.Point(14, 34)
};
var markerOptions = {
   icon: new H.map.Icon(iconUrl, iconOptions)
};
var marker = new H.map.Marker(coordinates, markerOptions);
map.addObject(marker);


var map = new H.Map(document.getElementById('map'),
  defaultLayers.normal.map);

// meine
window.addEventListener('resize', function () {
  map.getViewPort().resize();
});

var behavior = new H.mapevents.Behavior(new H.mapevents.MapEvents(map));

var ui = H.ui.UI.createDefault(map, defaultLayers);

moveMapToBerlin(map);`

**Comment by RyanPisuena** [comment]
https://developer.here.com/documentation/maps/topics/markers.html

``` javascript
// Create a map:
var map = new H.Map(...);

// Create a marker icon from an image URL:
var icon = new H.map.Icon('graphics/markerHouse.png');

// Create a marker using the previously instantiated icon:
var marker = new H.map.Marker({ lat: 52.5, lng: 13.4 }, { icon: icon });

// Add the marker to the map:
map.addObject(marker);
```
