### ISSUE TITLE
Stick dom marker in here maps on zooming 

### ISSUE THREAD

**Issue by dhruvsingh50** [heremaps/maps-api-for-javascript-examples#68]
I'm trying to add a truck Marker in the HERE Map. This marker is basically a truck icon. Here is my code.

 ```
 addDomMarker(posObj): void {
      const map = this.mapComponent.getMap();
      (window as any).mymap = map;
      const domIcon = new H.map.DomIcon(truckIcon);
      this.truckMarker = new H.map.DomMarker(posObj, {
           icon: domIcon
           });

      map.addObject(this.truckMarker);
      map.setCenter(posObj);
   }



 export const truckIcon = `<div class="truck-container">
 <svg class="truck-marker" id="truck"
      ...        // svg code 
 </svg></div>`;
```
Problem is when I'm zooming in or out, instead of sticking to the map , the dom marker is moving(animation).

Initial Position:
https://i.stack.imgur.com/qY3lj.png

After zoom out: ( black color dot is initial position.)

https://i.stack.imgur.com/lIR6i.png

After that it comes back to initial position. I want this marker to stick on the map rather that having animation. Is there any work around?

**Comment by germanz** [comment]
Hi. Try to specify the icon width, height, and anchor according to your SVG.
`
const svg = `<svg xmlns="http://www.w3.org/2000/svg" style="width: 28px; height: 28px; margin: -14px 0 0 -14px;" viewBox="0 0 100 100">
<circle cx="50" cy="50" r="50" fill="red" opacity=".5"/>
<circle cx="50" cy="50" r="4" fill="black"/>
</svg>`;

map.addObject(new H.map.DomMarker({lat: 52.51632137414747, lng: 13.378170368203042}, {
  icon: new H.map.DomIcon(svg)
}));
`

Full example: http://jsfiddle.net/54dkpajg/1/
