### ISSUE TITLE
Is there any way to change the color of the Infobubble?

### ISSUE THREAD

**Issue by jithu12** [heremaps/maps-api-for-javascript-examples#71]

**Comment by germanz** [comment]
Hi @jithu12. Sure, the default style of the UI controls comes from the[ **mapsjs-ui.css**](https://developer.here.com/documentation/maps/dev_guide/topics/map-controls-ui.html) file. You can  override it with a CSS like this:

```
/** Style for the info bubble content */
.H_ib_body {
  background: rgb(45, 213, 201);
}
/** Style for the info bubble tail */
.H_ib.H_ib_top .H_ib_tail::after {
    border-color: rgb(45, 213, 201) transparent;
}
```

Mind the order of that style and the **mapsjs-ui.css** on your page or alternatively use **!important**. Example: http://jsfiddle.net/029cd5pu/

**Comment by jithu12** [comment]
thanks man
