### ISSUE TITLE
Post Map Image with Polylines

### ISSUE THREAD

**Issue by joseBarreto** [heremaps/maps-api-for-javascript-examples#73]
Hello,
there is an alternative to Map Image with Polylines (https://developer.here.com/documentation/examples/rest/map-image/map-image-with-routes)
accepting Post?

By Get, we are breaking the URL limit.

**Comment by kplotnik** [comment]
Sorry, but Map Image API is completely different product. Please, address your question to one of the sources mentioned here https://developer.here.com/faqs#developer-support
