### ISSUE TITLE
Is there HERE Maps JS SDK available as repo?

### ISSUE THREAD

**Issue by vadym1930** [heremaps/maps-api-for-javascript-examples#81]
Can't find corresponding repo. Just wondering whether it is available for forking?

**Comment by vadym1930** [comment]
Can I fork repo with the, for example, the next source? https://js.api.here.com/v3/3.1/mapsjs-core.js

**Comment by ttobis** [comment]
Unfortunately **HERE Maps for JavaScript API** is not open sourced.

**Comment by timidak** [comment]
Is there an npm package available? We need geofencing for our TypeScript-Application and cannot find a suitable package. Is there a package for *HERE Maps for JavaScript API*?

**Comment by germanz** [comment]
@timidak HERE Maps API for JavaScript is not available as an NPM package yet.

You can try to use the [Fleet Telematics Geofencing API](https://developer.here.com/documentation/geofencing/dev_guide/topics/asset-distance-search-radius.html). There is a proxy class to communicate with that service from within the API. Check [H.service.extension.geofencing.Service](https://developer.here.com/documentation/maps/3.1.14.0/api_reference/H.service.extension.geofencing.Service.html).

**Comment by timidak** [comment]
@germanz 
Are you planning to release a npm package for the JavaScript API?

The api looks good 👍  Thank you! 
Is there another library or a standard for creating a polygon for the geometry of the fence? That would be the last thing we need. Thank you for your help!

**Comment by vadym1930** [comment]
@timidak You might want to see the example [HERE](https://developer.here.com/documentation/examples/maps-js/geoshapes/polygon-on-the-map).

**Comment by timidak** [comment]
Thank you @vadym1930, but I need another way to create such polygons. We cannot use the JavaScript API since it is not available as a npm package. Is there another way than the JS api?

**Comment by vadym1930** [comment]
@timidak sorry for the delay, it's been a crazy month. Honestly, I didn't get what you mean, if you are using HERE maps it's reasonable to me using their API for creating polygons if not, well you could use any lib you'd like for such a thing. 
Why you can't use CDNs though?

**Comment by germanz** [comment]
@timidak now you can install the library using **npm**. 

```
npm config set @here:registry https://repo.platform.here.com/artifactory/api/npm/maps-api-for-javascript/
npm i @here/maps-api-for-javascript
```
More information here:
https://developer.here.com/documentation/maps/3.1.16.1/dev_guide/topics/get-started-bundling.html
