### ISSUE TITLE
How do i get error response properly during route.calculateRoute({...}) ?

### ISSUE THREAD

**Issue by nriin-oji** [heremaps/maps-api-for-javascript-examples#84]
# What i use ?
- Reactjs
- Here maps for javascript

# My approach
My current approach to get calculated route are:
```javascript
useEffect(() => {
  ...
  try {
    route.calculateRoute(
      {
        ...config,
      },
      sucess => {
        console.log(success);
      },
      error => {
        console.log(error);
      },
    );
  } catch (e) {
    console.log(e);
  }
  ...
});

```
That way works, but the error object I received are not complete, it only return this object:
```javascript
//Error type that i got and able to process
Error: Error is NGEO_ERROR_ROUTE_NO_END_POINT
    at uq.a (eval at <anonymous> (mapsjs-core.js:71), <anonymous>:87:466)
    at eval (eval at <anonymous> (mapsjs-core.js:71), <anonymous>:87:176)
```

Based on here documentation, the error should return this object:
```javascript
//Error type returned from the network request BUT i cannot process the result(type, subtype)
{
   "_type":"ns2:RoutingServiceErrorType",
   "type":"ApplicationError",
   "subtype":"NoRouteFound",
   "details":"Error is NGEO_ERROR_ROUTE_NO_END_POINT",
   "additionalData":[
      {
         "key":"error_code",
         "value":"NGEO_ERROR_ROUTE_NO_END_POINT"
      }
   ],
   "metaInfo":{
      "timestamp":"2020-04-23T02:34:32Z",
      "mapVersion":"8.30.107.158",
      "moduleVersion":"7.2.202016-6899",
      "interfaceVersion":"2.6.76",
      "availableMapVersion":[
         "8.30.107.158"
      ]
   }
}
```
I only get the details message from it, well the thing is I didn't know all the details message unless for subtype NoRouteFound, am i missing something ?

Because of this issue, my current workaround is to make it general error, so when user facing all errors it will only show general message that currently you can't get the route calculation. 

They may wondering what exactly happened if I cannot give them proper message.

**Comment by oleksmarkh** [comment]
hi @nriin-oji! The `.calculateRoute()` doesn't throw an exception, so there's no need to wrap the call into `try...catch`. The `onError` callback is indeed supplied with the `details` part only and it's content is described in [Routing API docs - Error Data Types](https://developer.here.com/documentation/routing/dev_guide/topics/resource-types-error.html).

Unfortunately, at this point I could only suggest to parse the string you receive and map consts like `NGEO_ERROR_ROUTE_NO_END_POINT ` to specific error messages, plus having a generic error message fallback when parsing+mapping fails.
