### ISSUE TITLE
Load mapsjs-core.js dynamically cause H is not defined 

### ISSUE THREAD

**Issue by mostafa-raafat** [heremaps/maps-api-for-javascript-examples#89]
I have a problem using mapsjs-core.js v3.1 but the problem does not exist on v3.0
When i try to load here map dynamically i get the following error 

```var head = document.getElementsByTagName('head')[0],
        urls = ["https://js.api.here.com/v3/3.1/mapsjs-core.js",
            "https://js.api.here.com/v3/3.1/mapsjs-service.js",
            "https://js.api.here.com/v3/3.1/mapsjs-mapevents.js",
            "https://js.api.here.com/v3/3.1/mapsjs-ui.js"];

    urls.forEach(function (url) {
        var script = document.createElement('script');
        script.type = 'text/javascript';
        script.src = url;
        head.appendChild(script);
    });
```

```mapsjs-service.js:7 
Uncaught ReferenceError: H is not defined at mapsjs-service.js:7
mapsjs-service.js:7
mapsjs-mapevents.js:7 
Uncaught ReferenceError: H is not defined at mapsjs-mapevents.js:7
mapsjs-mapevents.js:7
mapsjs-ui.js:7 Uncaught ReferenceError: H is not defined at mapsjs-ui.js:7
```

**Comment by vadym1930** [comment]
Yeah, the thing is that `https://js.api.here.com/v3/3.1/mapsjs-core.js` is not there when `https://js.api.here.com/v3/3.1/mapsjs-service.js` already there. It's because of the core script really heavier compare ~261kb vs ~31.3kb. Solved the same issue with loading scripts synchronously. 

Or just load core one, then does not matter, others can be loaded in parallel.

**Comment by germanz** [comment]
@vadym1930 suggestion is correct. All modules depend from **mapsjs-core.js**, so it has to be loaded first. Alternatively, you can use also a single bundle **mapsjs.bundle.js** which contains all modules. It can be imported as an ES6 module. More on that here:
https://developer.here.com/documentation/maps/3.1.16.1/dev_guide/topics/get-started.html
