### ISSUE TITLE
Can't install npm package

### ISSUE THREAD

**Issue by LocalHeroPro** [heremaps/maps-api-for-javascript-examples#93]
As I described in [that](https://stackoverflow.com/questions/62729624/cant-install-here-api-for-javascript-from-package-json) topic I can't install your package from npm.

**Comment by kplotnik** [comment]
The package is in the HERE repository, please configure your npm:
`npm config set @here:registry https://repo.platform.here.com/artifactory/api/npm/maps-api-for-javascript/`
See https://developer.here.com/documentation/maps/3.1.17.0/dev_guide/topics/get-started-bundling.html for the more information about bundling
